version : '3.1'

#MongoDB , postgres, redis, Elasticsearch, kibana , Mysql
services :
  mongo :
    image : mongo
    restart : always
    environment :
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : root

